# Generated by Django 4.2.2 on 2024-09-07 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client_servis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Тема письма')),
                ('description', models.TextField(verbose_name='Тело письма')),
            ],
        ),
        migrations.CreateModel(
            name='Mailing_list',
            fields=[
                ('date_and_time_of_first_attempt', models.DateTimeField(auto_now_add=True, verbose_name='Дата первой отправки рассылки')),
                ('periodicity', models.CharField(max_length=25, verbose_name='Периодичность')),
                ('status', models.CharField(max_length=25, verbose_name='Статус')),
                ('data_next_shipping', models.DateTimeField(verbose_name='Дата следующей отправки')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='message', serialize=False, to='main.message', verbose_name='Сообщение')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to='main.client_servis', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Attempt_to_send',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time_of_last_attempt', models.DateTimeField(verbose_name='Дата и время следующей отправки')),
                ('status_attempt', models.CharField(max_length=20, verbose_name='Статус попытки')),
                ('mail_server_response', models.CharField(max_length=50, verbose_name='Ответ почтового сервера')),
                ('mailing_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailing_list', to='main.mailing_list', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылок',
            },
        ),
    ]
