# Generated by Django 4.2.2 on 2024-09-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing_list',
            name='periodicity',
            field=models.CharField(choices=[('DAILY', 'раз в день'), ('WEEKLY', 'раз в неделю'), ('MONTHLY', 'раз в месяц')], max_length=25, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='mailing_list',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создана'), ('STARTED', 'Запущена'), ('FINISHED', 'Завершена')], max_length=25, verbose_name='Статус'),
        ),
    ]
