# Generated by Django 4.2.2 on 2024-09-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_mailing_list_periodicity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing_list',
            name='client',
        ),
        migrations.AlterField(
            model_name='mailing_list',
            name='data_next_shipping',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата следующей отправки'),
        ),
        migrations.AlterField(
            model_name='mailing_list',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создана'), ('STARTED', 'Запущена'), ('FINISHED', 'Завершена')], default='Создана', max_length=25, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='mailing_list',
            name='client',
            field=models.ManyToManyField(blank=True, null=True, related_name='client', to='main.client_servis', verbose_name='Клиенты'),
        ),
    ]
