# Generated by Django 4.2.2 on 2024-09-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_mailing_list_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing_list',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активная'),
        ),
    ]
