# Generated by Django 4.2.2 on 2024-09-24 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mailing_list_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt_to_send',
            name='date_and_time_of_last_attempt',
        ),
    ]
