# Generated by Django 4.2.2 on 2024-09-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_attempt_to_send_date_and_time_of_last_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt_to_send',
            name='mail_server_response',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ответ почтового сервера'),
        ),
        migrations.AlterField(
            model_name='attempt_to_send',
            name='status_attempt',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Статус попытки'),
        ),
    ]
