# Generated by Django 4.2.2 on 2024-09-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_attempt_to_send_mail_server_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt_to_send',
            name='date_and_time_of_last_attempt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последней отправки'),
        ),
    ]
