# Generated by Django 4.2.2 on 2024-09-30 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_attempt_to_send_date_and_time_of_last_attempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
