# Generated by Django 4.2.2 on 2024-09-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing_list',
            name='client',
            field=models.ManyToManyField(related_name='client', to='main.client_servis', verbose_name='Клиенты'),
        ),
    ]
