# Generated by Django 4.2.2 on 2024-09-30 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_mailing_list_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing_list',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing_list',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='messages', serialize=False, to='main.message', verbose_name='Сообщение'),
        ),
    ]
