# Generated by Django 4.2.2 on 2024-10-02 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_client_servis_owner_mailing_list_owner_message_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing_list',
            options={'permissions': [('set_active', 'Can active mailing_list')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
